### ISSUE TITLE
Deserialization throws stack empty exception

### ISSUE THREAD

**Issue by ricebus** [YAXLib/YAXLib#83]
Hey, I've started using YAXLib to serialize/deserialize my classes.

I have an issue where the deserialization process throws a weird exception
``
{System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at YAXLib.YAXSerializer.FinalizeNewSerializer(YAXSerializer serializer, Boolean importNamespaces, Boolean popFromSerializationStack)
   at YAXLib.YAXSerializer.DeserializeCollectionValue(Type colType, XElement xelemValue, XName memberAlias, YAXCollectionAttribute colAttrInstance)
   at YAXLib.YAXSerializer.DeserializeCollectionMember(Object o, MemberWrapper member, Type colType, String elemValue, XElement xelemValue)
   at YAXLib.YAXSerializer.RetreiveElementValue(Object o, MemberWrapper member, String elemValue, XElement xelemValue)
   at YAXLib.YAXSerializer.DeserializeBase(XElement baseElement)
   at YAXLib.YAXSerializer.Deserialize(String input)
   at Hermes.Hermes.XmlToNcp() in C:\Users\George\documents\visual studio 2017\Projects\Hermes\Hermes\Hermes.cs:line 119}
``
The funny thing is that if I run it through deserilization a second time, it works.
Here's the XML it's trying to deserialize: https://pastebin.com/nKyhAnDe (in readable mode)

EDIT: forgot to mention it only happens in large strings. this one is about 19k chars long.

Thanks in advance,
George

**Comment by sinairv** [comment]
Hi George. Could you also please send the code, or the entities with attributes you use to deserialize the content?

**Comment by ricebus** [comment]
[Base.zip](https://github.com/sinairv/YAXLib/files/1252604/Base.zip)

The entity is NCPPacket

**Comment by ricebus** [comment]
any luck with this?

**Comment by axunonb** [comment]
Sorry @ricebus, this has been a long time ago.

We're about to revitalizing this project, now going through open issues.
At the moment, [the C# files](https://github.com/sinairv/YAXLib/files/1252604/Base.zip) and [XML sample](https://pastebin.com/nKyhAnDe) you had supplied cannot be built. To much guessing about dependencies.
If you're still interested, would you please complete the sample project attached to this post, or close the issue, if not?

[DeserializationEmptyStackException.zip](https://github.com/YAXLib/YAXLib/files/6057726/DeserializationEmptyStackException.zip)

**Comment by axunonb** [comment]
Closed due to lack of activity.
